baseurl = "https://loudcapital.com/"
googleAnalytics = ""
languageCode = "en-us"
publishDir = "public"
title = "Loud Capital"
canonifyURLs = true
[params]
custom_css = []
custom_js = []
description = "LOUD Capital is an entrepreneurial collective that empowers entrepreneurs and investors with capital, talent, and connections necessary to amplify success."
disableFonts = false
favicon = "favicon.ico"
name = "Michael Gerace"
[params.about]
enable = true
endpoint = "Who<br>we<br>are"
subtitle = "LOUD Capital is an entrepreneurial collective that empowers entrepreneurs and investors with capital, talent, and connections necessary to amplify success."
title = "About"